/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_head = new javax.swing.JLabel();
        btn_lgout = new javax.swing.JButton();
        btn_ureg = new javax.swing.JButton();
        btn_breg = new javax.swing.JButton();
        btn_bissue = new javax.swing.JButton();
        btn_breturn = new javax.swing.JButton();
        btn_inq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_head.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lbl_head.setText("    LIBRARY  MANAGEMENT  SYSTEM ");

        btn_lgout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_lgout.setText("Log Out");
        btn_lgout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lgoutActionPerformed(evt);
            }
        });

        btn_ureg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ureg.setText("User Registration");
        btn_ureg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uregActionPerformed(evt);
            }
        });

        btn_breg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_breg.setText("Book Registration");
        btn_breg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bregActionPerformed(evt);
            }
        });

        btn_bissue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_bissue.setText("Book Issue");
        btn_bissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bissueActionPerformed(evt);
            }
        });

        btn_breturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_breturn.setText("Book Return");
        btn_breturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_breturnActionPerformed(evt);
            }
        });

        btn_inq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_inq.setText("Inquiry");
        btn_inq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_head, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lgout)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_ureg)
                        .addGap(167, 167, 167)
                        .addComponent(btn_breg)
                        .addGap(178, 178, 178)
                        .addComponent(btn_bissue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btn_breturn)
                        .addGap(196, 196, 196)
                        .addComponent(btn_inq)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_head, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_lgout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ureg)
                    .addComponent(btn_breg)
                    .addComponent(btn_bissue))
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_breturn)
                    .addComponent(btn_inq))
                .addGap(0, 545, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lgoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lgoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login ob=new login();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_lgoutActionPerformed

    private void btn_bregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bregActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        book_registration ob=new book_registration();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_bregActionPerformed

    private void btn_uregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uregActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        registration ob=new registration();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_uregActionPerformed

    private void btn_bissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bissueActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        issue ob=new issue();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_bissueActionPerformed

    private void btn_breturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_breturnActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        breturn ob=new breturn();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_breturnActionPerformed

    private void btn_inqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inqActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        inq ob=new inq();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_inqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bissue;
    private javax.swing.JButton btn_breg;
    private javax.swing.JButton btn_breturn;
    private javax.swing.JButton btn_inq;
    private javax.swing.JButton btn_lgout;
    private javax.swing.JButton btn_ureg;
    private javax.swing.JLabel lbl_head;
    // End of variables declaration//GEN-END:variables
}
